webserver:
  image: wordpress
  ports:
    - "80:80"
  links:
    - "dbserver:mysql"

dbserver:
  image: mysql
  depends_on:
    - webserver
  volumes_from:
    - storage
  environment:
    MYSQL_ROOT_PASSWORD: password
